### PR TITLE
fix installer: wrong detection of hot signer usage.

### PR DESCRIPTION
**Pull request by edouardparis**
We did not check that the keys in the primary path were using the hot signer. In the case of a hot signing key only used for the primary path,
the hot signer was not advertised to the context
passing to each installer step and was not stored after install.

### CODE REVIEW

**Comment by darosior** [comment]
Successfully tested i'm now asked for the mnemonic even if i pick a hot key only for the primary path. However i wonder if there isn't a less brittle way of checking if we need to store / display the mnemonics than relying on a `signer_is_used` to be set. It seems to me to be a huge footgun: we may be missing other (potentially intricate!) instances where it is set now, and we might forget to set it in the future. I'm fine with a patch like this for 0.3, but for 0.4 let's try to make this code more robust?

**Comment by darosior** [comment]
Yeah i think it's best if we always use the descriptor as the source of truth. The computation should be reasonable.

**Comment by edouardparis** [comment]
Can we merge this fix and think about a way to harden the installer flow after the multipath feature ? I would be easier for me

**Comment by darosior** [comment]
ACK 2cbdf5bb32b711ea6057141c553b74ec810d9f0d

**Pull request merged**
