### PR TITLE
gui(installer): apply wording changes to installer templates

### LINKED ISSUE #1418: Wording corrections for installer flow
We had a joined discussion and this are the main wording points that can be worth tackling for this release. Other UX/UI improvements will be managed separately:

- Landing page: try to add "Liana" before "wallet" in both "Create a new wallet" and "Add an existing wallet" and see if it fits or if that's too long. This is to avoid confusion since a user reported that, since he wanted to use a hardware "wallet" already in his possess, he thought that "Add an existing wallet" was the right flow. Alternatively we could think of something like "+ new Liana wallet" and "+ existing Liana wallet"
- Choose wallet step: remove the sentence before the different template options since it is not very useful and clear.
- Change the name and description of the multisig template to: 
"Expanding Multisig
Two keys required to spend, with an extra key as a backup."
- Change the name of the custom template to: "Build your own"
- In the Simple Inheritance introduction page:
   - Add "Simple" before "Inheritance" to the title
   - Change the first sentence to: "For this setup you will need 2 keys: a Primary Key (for yourself) and an Inheritance Key (for your heir). For security reasons, we suggest you use a separate Hardware Wallet for each key."
   - Delete the "Give it to your heir(s) in order to be able to collect their inheritance." part in the second sentence
   - Change the svg with the new one: https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=580-5674&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the Expanding Multisig introduction page:
   - Change the title to "Expanding Multisig wallet"
   - Change the first sentence to: "For this setup you will need 3 keys: two Primary Keys and a Recovery Key.  For security reasons, we suggest you use a separate Hardware Wallet for each key."
   - Change the second sentence to: "The Primary Keys will compose a 2-of-2 multisig which will be always able to spend. In case one of your keys becomes unavailable, after a period of inactivity you will be able to recover your funds using the Recovery Key together with one of your Primary Keys (2-of-3 multisig)."
   - Change the svg with the new one: https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=528-5494&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the Build your own introduction page:
   - Change the title to "Build your own"
   - Change the sentences and svg according to the following mockup (@jp1ac4 feel free to edit some wording. I chose using the word "policy" because it seemed to be the most adapt to me): https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=1-11564&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the "Build your own" "Set keys" page:
   - Remove the introductory sentences to the paths and just leave the boxes with headings
   - Try editing the text of the "Add key" and "Add recovery path" to "Add another key" and "Add another recovery path" and see if they don't get too big (possible alternatives: just "+ Another key" and "+ Another recovery path")

### PR DESCRIPTION
**Pull request by jp1ac4**
This is to resolve #1418.

### CODE REVIEW

**Comment by jp1ac4** [comment]
I still need to:
- [ ] Update SVGs

**Comment by pythcoiner** [comment]
image

**Comment by pythcoiner** [comment]
image

**Comment by pythcoiner** [comment]
image

**Comment by pythcoiner** [comment]
image

Here the sentence is not exactly the one requested:
> Change the first sentence to: "For this `setup` you will need 2 keys: a Primary Key (for yourself) and an Inheritance Key (for your heir). For security reasons, we suggest you use a separate Hardware Wallet for each key."

`setup` vs `Inheritance wallet`, but maybe this is wanted/better?

**Comment by pythcoiner** [comment]
image

**Comment by nondiremanuel** [comment]
> Here the sentence is not exactly the one requested:
> 
> > Change the first sentence to: "For this `setup` you will need 2 keys: a Primary Key (for yourself) and an Inheritance Key (for your heir). For security reasons, we suggest you use a separate Hardware Wallet for each key."
> 
> `setup` vs `Inheritance wallet`, but maybe this is wanted/better?

I would use "setup" for consistency with the other introduction pages.

**Comment by pythcoiner** [comment]
nit: titles vs texts are not aligned, and it looks to me the title are too close from the radiuses
image

**Comment by pythcoiner** [comment]
nit2: i'd keep `Add another key` & `Add another recovery option` as i dont think we use `+` elsewhere

**Comment by jp1ac4** [comment]
> `will be always able` vs `will always be able`

Oh yes, well spotted :) I changed this to the latter as I think it's more common this way and that's how I kept trying to read it.

> nit: titles vs texts are not aligned, and it looks to me the title are too close from the radiuses

I haven't made any changes for this. Shall we move it to a new issue?

> I still need to:
> 
>     * [x]  Update SVGs

SVGs have been updated.

> I would use "setup" for consistency with the other introduction pages.

Done.

> Looking at it, I would probably drop the "another", especially when adding a key. It was useful to see how it looks, but I don't think it adds much value compared to the disadvantage of having a word more.

I dropped the commit that changed the wording of the "Add key" and "Add recovery option" buttons.

**Comment by nondiremanuel** [comment]
> > nit: titles vs texts are not aligned, and it looks to me the title are too close from the radiuses
> 
> I haven't made any changes for this. Shall we move it to a new issue?
> 

Yes we can manage it as a different UI improvement.

**Comment by pythcoiner** [comment]
updated screenshot @ f4b4afbb6cfba6f847b4c6e0d864fd2ffbca9a40:
image

image

image
image

image
image

image
image

image

**Comment by pythcoiner** [comment]
tACK f4b4afbb6cfba6f847b4c6e0d864fd2ffbca9a40

**Comment by jp1ac4** [comment]
Rebased on master.

**Review by edouardparis — APPROVED** [review]
ACK 9a3bc87a755d8290f2b89847431a0fe2eb889370

**Pull request merged**
