### PR TITLE
Add refresh coins buttons

### LINKED ISSUE #192: Homepage alert about coins epiry should link to "send" with pre-filled inputs and output
*To be tackled after #443.*

At the moment the user would have to figure out they need to create a spend transaction for those and do this manually.

### LINKED ISSUE #371: "Refresh" on each entry in coin list
*To be tackled after #192.*

The button would create a transaction that sends-to-self the coin.

### PR DESCRIPTION
**Pull request by edouardparis**
Fixes #371.
Fixes #192.

### CODE REVIEW

**Comment by darosior** [comment]
Rebased and used Liana's master now that #477 is merged.

**Comment by darosior** [comment]
Hmm somehow my push wasn't taken into account. Lemme investigate.

**Comment by darosior** [comment]
tested ACK 79984718bc65c3b536255e3737852de4aa3049d5

It's great.

**Comment by darosior** [comment]
CI failure seems unrelated to this PR: `error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1038:9: no MIR available for DefId(30:2756 ~ wgpu_core[1c42]::track::buffer::{impl#0}::all_ordered)`.

**Comment by edouardparis** [comment]
Seems that compiling wgpu on nightly is broken on MacOS

**Comment by darosior** [comment]
> Seems that compiling wgpu on nightly is broken on MacOS

It's failing on Ubuntu though?

> curious if https://github.com/wizardsardine/liana/commit/15633865c4bbb28815c894984e2c740eed486b9a fix the problem

Try to cherry-pick it here?

**Comment by darosior** [comment]
re-ACK aa23bba9d48b3ce683c7090c7d7ab8c6e218868d

Thanks for fixing the CI.

**Pull request merged**
