### PR TITLE
installer: add a warning modal if remote address is not loopback

### LINKED ISSUE #1059: [Remote bitcoind] wallet name is create in /home/<user>/.liana
liana

here my username on laptop is `pythliana`, bitcoind on remote running under `pyth` user, so we ask bitcoind to create the wallet at `/home/pythliana/.liana` on remote, but it's out of remote userspace so it fails

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR add a warning modal if user try to connect to a non-loopback address & use RPCAuth:

image

It also add a check on address + RPC user/password: 
`Check connection` button is greyed out until address is valid + user and password are filled (if RPCAuth selected)

Closes #1059 

 - [x] better check of valid address, atm `::1:<port>` fail but should not (IPV6 loopback)

### CODE REVIEW

**Comment by nondiremanuel** [comment]
Does this address also #1046 or will it need another PR?

**Comment by nondiremanuel** [comment]
Thanks for taking this PR! A couple of questions/comments more on the "UI" side:

- Why is the font green? It doesn't give me the idea of a warning at first glance (or is it maybe a standard that we already use for warnings? Do we have one?)
- Wording: "if you are confident in your actions" doesn't say much in my opinion. If the remote bitcoind is not supported as we say in the first sentence, how could confidence fix it? Either we support it but requires expertise or not support it. Am I missing something?
In general, the second sentence doesn't seem very useful to me. If the purpose of the warning is to warn the user about remote bitcoind while not blocking them, I think the first sentence already accomplishes it. We could just change the "Continue" button to "Proceed anyway" or something like this. But maybe I'm missing something more that we want to communicate to the user.

**Comment by pythcoiner** [comment]
> * Why is the font green? It doesn't give me the idea of a warning at first glance (or is it maybe a standard that we already use for warnings? Do we have one?)
because i'm not good at design stuff :grin:. Which color should we use? (i think red is more for error)

> * Wording: "if you are confident in your actions" doesn't say much in my opinion. If the remote bitcoind is not supported as we say in the first sentence, how could confidence fix it? Either we support it but requires expertise or not support it. Am I missing something?
>   In general, the second sentence doesn't seem very useful to me. If the purpose of the warning is to warn the user about remote bitcoind while not blocking them, I think the first sentence already accomplishes it. We could just change the "Continue" button to "Proceed anyway" or something like this. But maybe I'm missing something more that we want to communicate to the user.

I'm also not good at wording :grin:! i ask gpt to reword me, but it seems he's not better than me...

The mean is there is some special case where the user have to connect it's local machine w/ a local IP (nixOS?, VM, Docker, etc...), so it looks like an external IP, but only the (advanced) user know it, we cannot determine it. I dont think we should put much more details here, but maybe we should document it (or not).

Feel free to advise me wording, i'll be happy to replace mine!

**Comment by pythcoiner** [comment]
> Does this address also #1046 or will it need another PR?

I think we can also close it if this PR merged, as technicaly we cannot remove the wo wallet on the remote (we do not have access to the remote filesystem and bitcoind does not have a command for this) and the only thing we can do is avaoid the user to create it (it's what we do in this PR) (and maybe document it)

**Comment by nondiremanuel** [comment]
> >   because i'm not good at design stuff 😁. Which color should we use? (i think red is more for error)

If we have other warning modals in the application (if so, I don't remember how they are formatted), I would align it to those. Usually a warning symbol close to the "Warning" title of the modal, leaving the font white could be enough. Alternatively, I would use yellow.

> I'm also not good at wording 😁! i ask gpt to reword me, but it seems he's not better than me...
> 
> The mean is there is some special case where the user have to connect it's local machine w/ a local IP (nixOS?, VM, Docker, etc...), so it looks like an external IP, but only the (advanced) user know it, we cannot determine it. I dont think we should put much more details here, but maybe we should document it (or not).
> 
> Feel free to advise me wording, i'll be happy to replace mine!

In order to understand which could be the warning, what happens if the user inserts a remote node IP and still decides to go on ignoring the warning? Do we throw an error or something?

**Comment by darosior** [comment]
For the warning i was thinking of a simple line (in yellow for instance, but i'm not sure about the color) displayed next to the text input for the ip.

-------- Original Message --------

**Comment by pythcoiner** [comment]
> In order to understand which could be the warning, what happens if the user inserts a remote node IP and still decides to go on ignoring the warning? Do we throw an error or something?

4 issues are described at start of this [comment](https://github.com/wizardsardine/liana/issues/1059#issuecomment-2179757148)

**Comment by pythcoiner** [comment]
> For the warning i was thinking of a simple line (in yellow for instance, but i'm not sure about the color) displayed next to the text input for the ip.
> […](#)

My 2 points for the modal are:
- they cannot miss the warning
- if they choose cancel we automatically reload default ip:port values in the address field

**Comment by pythcoiner** [comment]
there is no yellow color defined in liana [theme](https://github.com/wizardsardine/liana/blob/master/gui/ui/src/color.rs), anyone to pick one? (i'm color blind, so not easy for me :grin:)

**Comment by nondiremanuel** [comment]
I would personally go for the yellow sentence (as in the #1141) since it is less intrusive for the user and at the same time accomplishes to communicate the message. Regarding the wording, I would use something like:

"Connection to a remote bitcoin node is not supported. Insert an IP address bound to the same machine running Liana (ignore this warning if that's already the case)"

or some variant of it (I'm not sure about the verb "bind" for an IP address. "Belonging to"? "Used by"? Else?)

**Comment by nondiremanuel** [comment]
> there is no yellow color defined in liana [theme](https://github.com/wizardsardine/liana/blob/master/gui/ui/src/color.rs), anyone to pick one? (i'm color blind, so not easy for me 😁)

The one in the other PR seems good to me. Maybe I would make the font a little bigger

**Comment by nondiremanuel** [comment]
The alternative solution (#1141) was merged, so I close this PR

**Pull request closed without merging**
