### PR TITLE
Set network in launcher

### LINKED ISSUE #306: GUI installer: add a previous button
Currently, when a wallet is already set, clicking on "Install Liana on another network" opens the installer, with no way to go back.
If you miss click, you have to close and open the app, that's bad.

Adding a previous button, only when the user came from the launcher screen, would fix this.

I tried but didn't find a way to do it, while keeping the current UI, with the 3 buttons staying in the center of the screen.
So either :
 - Find a way to do it probably by using another layout than Row or Column
 - Add the previous button in the middle of the screen too
 - Put everything on the top of the screen

image

### PR DESCRIPTION
**Pull request by edouardparis**
This Pull requests introduce three changes:

1. Network can only be chosen with the launcher panel. A drop down showing what network user can install is shown to the user when clicking on install a new network.
2. A previous button is added to the first installer page, so user can be redirected to launcher and the network choices if he has chosen the wrong network. close #306 
3. In order to make it clear for the user which network he is actually using or he is currently installing a blue banner is added on top of the window if the network is different than the bitcoin mainnet.

20240529_13h01m15s_grim
20240529_13h01m27s_grim
20240529_13h01m02s_grim
20240529_13h00m35s_grim

### CODE REVIEW

**Comment by darosior** [comment]
Here: 
image

nit: i think it would be clearer if the two sections were:
- Open an existing wallet
- Create a new wallet

It's already obvious from the options the user has to select a network. I think it's more helpful to tell the user what the selection would achieve.

**Comment by jp1ac4** [comment]
It looks very nice :heart_eyes:

After deleting an existing wallet, the list of networks for a new install does not refresh to include the deleted network.

It would be nice to refresh this list even while the modal is open:
image

Regarding the "Change network" button, this is also covered as part of #993. There are some other special cases to consider, e.g. if the network has been specified in the command line, it may not make sense to show the button.

The only other thing I found is that the default window size may make the list not display nicely, e.g.
image

This is resolved if the window is made bigger.

**Comment by darosior** [comment]
This is the screen i get on the first launch on a fresh datadir:
image

We shouldn't tell "Welcome back". Only "Welcome" works i guess?

We should not have the "Select network" section, since there is no existing wallet. We should have the "Install on mainnet" by default, with a small line inviting to install on another network (by selecting which one from a dropdown). As per the mockups:
image

Also had the same issue as Michael above:
image

In addition, again "Select network" should not be there if there is no installed wallet.

**Comment by nondiremanuel** [comment]
I would propose adding a back symbol ("<" or something equivalent) in the "Change Network" button to indicate that, by clicking it, the user would be redirected to the previous step.

**Comment by jp1ac4** [comment]
Deletion of existing wallet works nicely now and the list of networks is displaying well on the default window size.

I found that if I use a new data directory, I get an error in the logs when selecting the network to use:
```
ERROR liana_gui::logger: Failed to change logger settings: Io(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)
```
and then after completing the installer:
```
ERROR liana_gui::logger:102: Failed to remove installer log file /home/michael/test/liana/gui/abcdef/installer.log error:Os {
    code: 2,
    kind: NotFound,
    message: "No such file or directory",
}
```

**Comment by darosior** [comment]
Sorry for nitpicking, but now it's not very clear what's happening.
image

Could this read "Install Liana on Bitcoin mainnet"? Or better yet not mention mainnet at all, some would not know what "mainnet" is (i can already see from here the question "is that a shitcoin?").

Ideally i think we would have something like a button which reads something like "Create a Liana wallet" with like a right-facing arrow. And then below, in a smaller font, some text which reads "Select a different network". Clicking on this text would expand the list of networks. Selecting one of the network would collapse the list and change the Bitcoin logo in the main "Create a Liana wallet" button. What do you think? Am i making sense?

Alternatively, we can try going for something simpler which wouldn't have you re-implement multiple components. But i'm not sure what. Right now it's very confusing. The user can't understand what clicking on the button is going to achieve for them.

**Comment by edouardparis** [comment]
> Ideally i think we would have something like a button which reads something like "Create a Liana wallet" with like a right-facing arrow. And then below, in a smaller font, some text which reads "Select a different network". Clicking on this text would expand the list of networks. Selecting one of the network would collapse the list and change the Bitcoin logo in the main "Create a Liana wallet" button. What do you think? Am i making sense?

Only in the case of it is a fresh install and no other wallet is created ?
I think it adds one useless clicks, once the list of network is expanded, user should just click on it to start the install.

**Comment by darosior** [comment]
Maybe. Do you have another suggestion? I don't think users should see "mainnet". And they should know what clicking on the button is going to do.

I'm also trying to think through an alternative which would be less time consuming to implement. Do you have an idea? Maybe just a label before the "Bitcoin mainnet" button which reads "Create a new Liana wallet:"? This is ugly, we keep mainnet, but it's simple.

**Review by jp1ac4 — APPROVED** [review]
Tested ACK https://github.com/wizardsardine/liana/pull/1098/commits/c0e7b63809fd60f4fc6f5e9cd5223c138e25cfde.

**Pull request merged**
