### PR TITLE
gui: skip register step if no device used

### LINKED ISSUE #400: Installer: do not make them check device registration of the descriptor if there is no device
It keeps confusing people that use the wallet without a signing device.

### PR DESCRIPTION
**Pull request by jp1ac4**
This is to resolve #400.

Thanks to @edouardparis for the suggestions and code snippets provided that form the basis of these changes.

I'm opening this PR as draft so you can see my progress and check in case I've missed anything or you'd like some tests added.

Based on my own tests with and without devices, this is working as expected.

### CODE REVIEW

**Comment by jp1ac4** [comment]
OK sure, I'll give that a try. Would it also be worth adding some assertions to the existing test?

**Comment by jp1ac4** [comment]
I've made an initial attempt at a test to check that the bool `hw_is_used` is being set correctly in a few different cases. Please let me know if this is along the right lines.

I've also rebased on master.

Thanks.

**Comment by edouardparis** [comment]
Tested and everything seems fine.
However when importing a descriptor while participating in a shared setup or recovering a wallet, the registration step is not shown anymore. Can you modify ImportDescriptor.apply by setting ctx.hw_is_used to true with a comment please ?
```
// Set to true in order to force the registration process to be shown to user.
ctx.hw_is_used = true;
```

**Comment by jp1ac4** [comment]
Thanks for your feedback.

I've now added those lines before the `if` expression in the `apply` method, but can move it within the `if` expression if you prefer. I checked that the registration step now appears when importing a descriptor.

I've squashed my commits to a single commit and rebased on master.

**Review by edouardparis — APPROVED** [review]
ACK 38340c01898a8b19f84abe5e913cd0316d93a9c4

**Comment by edouardparis** [comment]
Good job :clap: 
The installer has sadly a lot of moving parts, but it went great.

**Comment by jp1ac4** [comment]
Thanks very much for all your help :pray:

**Pull request merged**
