### PR TITLE
gui(installer): align title & descrpition in path cards

### LINKED ISSUE #1427: Installer - Align text in "Set Keys" step
See: https://github.com/wizardsardine/liana/pull/1422#issuecomment-2454027609

### PR DESCRIPTION
**Pull request by pythcoiner**
fixes #1427
image

### CODE REVIEW

**Comment by jp1ac4** [comment]
On the topic of alignment, perhaps we could include this change to remove an empty space on the new line? Can also do in separate PR later.
```diff
diff --git a/gui/src/installer/prompt.rs b/gui/src/installer/prompt.rs
index 3eafa48a..7b216864 100644
--- a/gui/src/installer/prompt.rs
+++ b/gui/src/installer/prompt.rs
@@ -3,7 +3,7 @@ pub const BACKUP_DESCRIPTOR_HELP: &str = "In Bitcoin, the coins are locked using
 pub const DEFINE_DESCRIPTOR_PRIMARY_PATH_TOOLTIP: &str =
     "Set key(s) that can be used to spend coins immediately, with no time restriction.";
 pub const DEFINE_DESCRIPTOR_RECOVERY_PATH_TOOLTIP: &str =
-    "Set key(s) that can be used to spend coins after a defined period of time.\n Different sets of keys can be set to become available at different times.";
+    "Set key(s) that can be used to spend coins after a defined period of time.\nDifferent sets of keys can be set to become available at different times.";
 pub const DEFINE_DESCRIPTOR_FINGERPRINT_TOOLTIP: &str =
     "The alias is applied on all the keys derived from the same seed";
 pub const REGISTER_DESCRIPTOR_HELP: &str = "To be used with the wallet, a signing device needs the descriptor. If the descriptor contains one or more keys imported from an external signing device, the descriptor must be registered on it. Registration confirms that the device is able to handle the policy. Registration on a device is not a substitute for backing up the descriptor.";

**Review by jp1ac4 — APPROVED** [review]
tACK 875599ac3f9382c4e621f09c6fe5b0de7c07c751.

**Comment by pythcoiner** [comment]
i do now

**Comment by pythcoiner** [comment]
> On the topic of alignment, perhaps we could include this change to remove an empty space on the new line? Can also do in separate PR later.
> 
> ```diff
> diff --git a/gui/src/installer/prompt.rs b/gui/src/installer/prompt.rs
> index 3eafa48a..7b216864 100644
> --- a/gui/src/installer/prompt.rs
> +++ b/gui/src/installer/prompt.rs
> @@ -3,7 +3,7 @@ pub const BACKUP_DESCRIPTOR_HELP: &str = "In Bitcoin, the coins are locked using
>  pub const DEFINE_DESCRIPTOR_PRIMARY_PATH_TOOLTIP: &str =
>      "Set key(s) that can be used to spend coins immediately, with no time restriction.";
>  pub const DEFINE_DESCRIPTOR_RECOVERY_PATH_TOOLTIP: &str =
> -    "Set key(s) that can be used to spend coins after a defined period of time.\n Different sets of keys can be set to become available at different times.";
> +    "Set key(s) that can be used to spend coins after a defined period of time.\nDifferent sets of keys can be set to become available at different times.";
>  pub const DEFINE_DESCRIPTOR_FINGERPRINT_TOOLTIP: &str =
>      "The alias is applied on all the keys derived from the same seed";
>  pub const REGISTER_DESCRIPTOR_HELP: &str = "To be used with the wallet, a signing device needs the descriptor. If the descriptor contains one or more keys imported from an external signing device, the descriptor must be registered on it. Registration confirms that the device is able to handle the policy. Registration on a device is not a substitute for backing up the descriptor.";
> ```

@jp1ac4 done

**Review by jp1ac4 — APPROVED** [review]
tACK https://github.com/wizardsardine/liana/pull/1428/commits/636791d9484468c792bfe2022abfe68a6daf70e9.

**Comment by jp1ac4** [comment]
Oops, I'm really sorry but I forgot that I removed those prompts in #1422 :grimacing: You can drop the second commit. Sorry :pray:

**Review by jp1ac4 — APPROVED** [review]
tACK f6c953fb1dcf16b303d8382160dbbffbde060b2d.

**Pull request merged**
