### PR TITLE
Display details of wallet policy in installer

### LINKED ISSUE #620: Display the policy nicely (like in installer) in the settings
Such a great UI to create the wallet. 

Why not use the same interface to visualize what are the different recovery fallbacks are after creation?

### PR DESCRIPTION
**Pull request by edouardparis**
20240827_14h53m19s_grim
20240827_14h56m31s_grim

close #620

### CODE REVIEW

**Comment by nondiremanuel** [comment]
Thanks for implementing it! A couple of quick comments looking at the screenshots:
- I think we miss `'s` in the primary path: "can always spend this wallet**'s** funds ..."
- Why the first recovery path is "Recovery path # 0?
- In case of single sig, I think the "out of 1" part would be better to be omitted. But it's a minor thing and if it complicates the logic we can keep it as it is

Regarding the wording for recovery paths which was being discussed in the original issue, I agree with @jp1ac4's idea of referring to coins, but I believe that the concept of "older" for it can be tricky to understand for the user. I also agree on the fact that we should use a sentence as short as possible. I would prefer a way to more explicitly say what we mean by older, like "can recover coins not spent/refreshed for more than X blocks ..."

**Comment by edouardparis** [comment]
> can recover coins not spent/refreshed for more than X blocks ...

What do you think of "untouched" ?

**Comment by jp1ac4** [comment]
I agree that "untouched" could be ambiguous. I think "inactive" or perhaps "dormant" would be clearer.

**Comment by edouardparis** [comment]
> "inactive" or perhaps "dormant" would be clearer.

ACK for inactive

**Review by edouardparis — COMMENTED** [review]
Self-ACK 59e7131aeef4478933c6923155ed59535e218c96

**Pull request merged**
