### PR TITLE
gui: use patch for iced_futures

### LINKED ISSUE #684: GUI: after running a random amount of time we got lot of TrySendError full errors in the logs and a freeze
While listening for close request in the application subscription, it seems that the subscription tracker is clogged.

### PR DESCRIPTION
**Pull request by edouardparis**
close #684

### CODE REVIEW

**Review by darosior — APPROVED** [review]
From my limiting reading and understanding of Iced and Winit, your patch makes sense to me. We definitely need to keep the discussion in https://discourse.iced.rs/t/a-problem-and-a-possible-solution-for-clogged-mpsc-channel-in-iced-futures/50 going though, as we may be missing something.

I need to look into adapting the GUIX build to your patched Iced, that shouldn't be too complicated.

**Comment by darosior** [comment]
This also needs testing on Windows, @kloaec will take care of this in about a hour.

**Comment by darosior** [comment]
ACK 3019608

**Comment by darosior** [comment]
You probably want to PR this to master as well?

**Comment by darosior** [comment]
If you do, maybe also include #687.

**Comment by edouardparis** [comment]
Yes, doing it right now

**Pull request merged**
