### PR TITLE
[GUI] fixed size/position for PSBT badges

### LINKED ISSUE #509: Spent label missaligned in PSBTs
While in the PSBTs section, the Spent label does not alight at the same point for "send-to-selfs" as it does to "normal" spends.

Seems the reason is because the reference point is the text shown on top of the miner fee.

Screenshot 2023-05-13 at 04 27 21

### PR DESCRIPTION
**Pull request by pythcoiner**
this PR try to fix #509
i refactored some badges , moving (optional) `batch` badge before mandatory ones and give fixed positions/size for mandatory badges

before:

image

after:

image

### CODE REVIEW

**Comment by jp1ac4** [comment]
I like how this looks now. Should we use this new badge size also when viewing an individual PSBT?

image

**Comment by pythcoiner** [comment]
i'm not sure anyone notice this change on psbt, as the badge in alone in the top right corner, but we can

**Comment by darosior** [comment]
The before/after screenshots look amazing.

**Review by edouardparis — APPROVED** [review]
ACK e05e42136801e3168b99be378ae85e2852a8ccf6

I did a little refac to remove the need for `_sized` method. Thanks for the idea and the change.

**Pull request merged**
