### PR TITLE
Use 2 decimal for sync progression in home page

### PR DESCRIPTION
**Pull request by thomask7b**
Did the update for the home page.
For the loading screen (IBD) it was already formatting with 2 decimal, see `loader.rs:450`

Solves #907

### CODE REVIEW

**Comment by pythcoiner** [comment]
can you run:
```
cd gui && cargo update -p liana
```
in order to update the daemon dependency?

**Comment by pythcoiner** [comment]
tACK d9d93cc15b18fb37a774683f219973acc0025f88
image

**Review by jp1ac4 — APPROVED** [review]
tACK https://github.com/wizardsardine/liana/commit/d9d93cc15b18fb37a774683f219973acc0025f88.

Home page and loading screen are showing 2 decimal places.

Thanks!

**Comment by thomask7b** [comment]
Reopened #1465

**Pull request closed without merging**
