### PR TITLE
Gui show transaction detail while signing

### PR DESCRIPTION
**Pull request by edouardparis**
Fixes https://github.com/wizardsardine/liana/issues/644.

### CODE REVIEW

**Comment by darosior** [comment]
Wanted to take the opportunity of signing a mainnet transaction to try this, and this crashed.
```
  2023-12-08T09:05:09.118565Z ERROR liana:55: panic occurred at line 139 of file /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs: Some("called `Option::unwrap()` on a `None` value")                                                                                                                                                                                              
   0: liana::setup_panic_hook::{{closure}}                                                                                                                                                                                                                                                                                                                                                                                              
             at /home/darosior/.cargo/git/checkouts/liana-efb3a908181ef2cf/514535d/src/lib.rs:49:18                                                                                                                                                                                                                                                                                                                                     
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call                                                                                                                                                                                                                                                                                                                                                                   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9                                                                                                                                                                                                                                                                                                                                       
      std::panicking::rust_panic_with_hook                                                                                                                                                                                                                                                                                                                                                                                              
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13                                                                                                                                                                                                                                                                                                                                     
   2: std::panicking::begin_panic_handler::{{closure}}                                                                                                                                                                                                                                                                                                                                                                                  
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13                                                                                                                                                                                                                                                                                                                                     
   3: std::sys_common::backtrace::__rust_end_short_backtrace                                                                                                                                                                                                                                                                                                                                                                            
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18                                                                                                                                                                                                                                                                                                                          
   4: rust_begin_unwind                                                                                                                                                                                                                                                                                                                                                                                                                 
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5                                                                                                                                                                                                                                                                                                                                      
   5: core::panicking::panic_fmt                                                                                                                                                                                                                                                                                                                                                                                                        
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14                                                                                                                                                                                                                                                                                                                                     
   6: core::panicking::panic                                                                                                                                                                                                                                                                                                                                                                                                            
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5                                                                                                                                                                                                                                                                                                                                     
   7: core::option::Option<T>::unwrap                                                                                                                                                                                                                                                                                                                                                                                                   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:935:21                                                                                                                                                                                                                                                                                                                                       
   8: iced_lazy::component::Instance<Message,Renderer,Event,S>::rebuild_element_if_necessary::{{closure}}                                                                                                                                                                                                                                                                                                                               
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:135:33                                                                                                                                                                                                                                                                                                             
   9: iced_lazy::component::ouroboros_impl_state::State<Message,Renderer,Event,S>::new                                                                                                                                                                                                                                                                                                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:94:1                                                                                                                                                                                                                                                                                                               
  10: iced_lazy::component::ouroboros_impl_state::StateBuilder<Message,Renderer,Event,S,ElementBuilder_>::build                                                                                                                                                                                                                                                                                                                         
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:94:1                                                                                                                                                                                                                                                                                                               
  11: iced_lazy::component::Instance<Message,Renderer,Event,S>::rebuild_element_if_necessary                                                                                                                                                                                                                                                                                                                                            
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:128:17                                                                                                                                                                                                                                                                                                             
  12: iced_lazy::component::Instance<Message,Renderer,Event,S>::with_element_mut                                                                                                                                                                                                                                                                                                                                                        
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:206:9                                                                                                                                                                                                                                                                                                              
  13: iced_lazy::component::Instance<Message,Renderer,Event,S>::with_element                                                                                                                                                                                                                                                                                                                                                            
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:199:9                                                                                                                                                                                                                                                                                                              
  14: <iced_lazy::component::Instance<Message,Renderer,Event,S> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                                                                                                                                                                                                                                               
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_lazy-0.6.1/src/component.rs:258:9                                                                                                                                                                                                                                                                                                              
  15: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout::{{closure}}                                                                                                                                                                                                                                                                                               
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:169:17                                                                                                                                                                                                                                                                                                   
  16: iced_native::widget::container::layout                                                                                                                                                                                                                                                                                                                                                                                            
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:309:23                                                                                                                                                                                                                                                                                                   
  17: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                                                                                                                                                                                                                                            
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:158:9                                                                                                                                                                                                                                                                                                    
  18: iced_native::layout::flex::resolve                                                                                                                                                                                                                                                                                                                                                                                                
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:97:26                                                                                                                                                                                                                                                                                                         
  19: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                                                                                                                                                                                                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                                                                                                                                                                                                                                       
  20: iced_native::layout::flex::resolve                                                                                                                                                                                                                                                                                                                                                                                                
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:97:26                                                                                                                                                                                                                                                                                                         
  21: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                   
  22: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout::{{closure}}                                                                           
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:169:17                                                                               
  23: iced_native::widget::container::layout                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:309:23                                                                               
  24: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                        
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:158:9                                                                                
  25: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:97:26                                                                                     
  26: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                   
  27: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:97:26                                                                                     
  28: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                   
  29: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:97:26                                                                                     
  30: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                   
  31: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:136:26                                                                                    
  32: <iced_native::widget::row::Row<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                                    
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/row.rs:122:9                                                                                      
  33: <iced_native::widget::scrollable::Scrollable<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout::{{closure}}                                                                         
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/scrollable.rs:203:17                                                                              
  34: iced_native::widget::scrollable::layout                                                             
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/scrollable.rs:422:19                                                                              
  35: <iced_native::widget::scrollable::Scrollable<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                      
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/scrollable.rs:196:9                                                                               
  36: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout::{{closure}}                                                                           
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:169:17                                                                               
  37: iced_native::widget::container::layout                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:309:23                                                                               
  38: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                        
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/container.rs:158:9                                                                                
  39: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:136:26                                                                                    
  40: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                              
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/column.rs:133:9                                                                                   
  41: iced_native::layout::flex::resolve                                                                  
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/layout/flex.rs:136:26                                                                                    
  42: <iced_native::widget::row::Row<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout                                                                                                    
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/widget/row.rs:122:9                                                                                      
  43: <liana_ui::component::toast::Manager<Message> as iced_native::widget::Widget<Message,iced_graphics::renderer::Renderer<iced_glow::backend::Backend,liana_ui::theme::Theme>>>::layout                          
             at ui/src/component/toast.rs:44:9                                                            
  44: <iced_native::element::Map<A,B,Renderer> as iced_native::widget::Widget<B,Renderer>>::layout        
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/element.rs:287:9                                                                                         
  45: <iced_native::element::Map<A,B,Renderer> as iced_native::widget::Widget<B,Renderer>>::layout        
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/element.rs:287:9                                                                                         
  46: <iced_graphics::renderer::Renderer<B,T> as iced_native::renderer::Renderer>::layout                 
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_graphics-0.8.0/src/renderer.rs:61:22                                                                                       
  47: iced_native::user_interface::UserInterface<Message,Renderer>::build                                 
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_native-0.10.3/src/user_interface.rs:106:13                                                                                 
  48: iced_winit::application::build_user_interface                                                       
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:630:26                                                                                      
  49: iced_glutin::application::run_instance::{{closure}}                                                 
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_glutin-0.8.0/src/application.rs:327:43                                                                                     
  50: iced_glutin::application::run::{{closure}}                                                          

```

**Comment by darosior** [comment]
Punting this to v5, as this is a large diff, is still WIP (and crashing) and other things are higher priority.

**Comment by edouardparis** [comment]
wip, changed toast components after a rebase on #597

**Comment by edouardparis** [comment]
20240112_15h51m32s_grim
20240112_15h54m56s_grim

**Review by edouardparis — COMMENTED** [review]
Self-ACK 7d97f466ef174f5c9a7f57f757f737cf66ff5d81

**Pull request merged**
