### PR TITLE
electrum: don't roll the tip forward upon reorg

### PR DESCRIPTION
**Pull request by jp1ac4**
For Electrum, we detect reorgs while syncing based on our local chain.

When a user requests a rescan, we roll the DB back to genesis block, but leave the local chain as it is. If there's then a reorg, we would find the common ancestor with respect to our local chain, which would be later than the DB's tip. In order not to miss any updates, we shouldn't roll the DB tip forward in that case.

### CODE REVIEW

**Comment by darosior** [comment]
Just re-kicked all functional in CI to see if this really fixed it.

**Comment by darosior** [comment]
Concept ACK

**Comment by jp1ac4** [comment]
Note some failures for both bitcoind & electrs in PR rebased on current master:
https://github.com/wizardsardine/liana/pull/1303/checks?check_run_id=29991124649
https://github.com/wizardsardine/liana/pull/1303/checks?check_run_id=29991124486

**Comment by darosior** [comment]
Are we sure those are due to a roll-forward and would be fixed by this patch?

**Comment by jp1ac4** [comment]
> Are we sure those are due to a roll-forward and would be fixed by this patch?

Not sure at this stage. It may be something else due to bitcoind also failing.

**Comment by darosior** [comment]
Well i'm going to... Re-run with Terminal access!

**Review by darosior — COMMENTED** [review]
utACK 87593befd4a85accbab7e7417b322ea74393b69d.

I'd very much like to see a regression test for this in a followup.

**Comment by jp1ac4** [comment]
> I'd very much like to see a regression test for this in a followup.

Note to anyone implementing this: we need the poller to detect a rescan, roll the DB back to genesis block, and then for a reorg to occur before the next poller iteration starts so that a common ancestor with height > 0 is returned by `sync_wallet()` while the DB tip is still 0.

**Pull request merged**
