### PR TITLE
Bootstrappable builds

### PR DESCRIPTION
**Pull request by darosior**
This introduces reproducible and bootstrappable builds of our softwares by using [Guix](https://guix.gnu.org/). This is heavily inspired by the work on Guix [that was done in the Bitcoin Core project](https://github.com/bitcoin/bitcoin/tree/master/contrib/guix). For an intro to reproducible builds with Guix see [this post](https://guix.gnu.org/blog/2020/reproducible-computations-with-guix/).

For details, see the documentation introduced in this PR. Apologies for the poor commit history.

### CODE REVIEW

**Comment by darosior** [comment]
Alright, so i have a working script for both `lianad` and `liana-gui`. (Thanks Edouard for the suggestion to strip the ELF interpreter in addition to the RPATH!)

I'll add some doc around how to install Guix and use the script, then this will be ready for review.

**Comment by darosior** [comment]
Pushed some more improvements. Working on the documentation now.

**Comment by darosior** [comment]
Alright, i fixed the sometimes-missing dependencies of the GUI in the container, as well as removed from the doc a confusing reference to an environment variable we don't have.

Now i need to find the source of difference between Edouard's built binaries and mine.

**Comment by darosior** [comment]
Hashes for a build at 592c1cbaa8f4c1cd27f33a1600c8ddeac3add3b0:
```
darosior@darosior:~/projects/revault/liana$ sha256sum /tmp/tmp.oda7hUDyqL/out/release/lianad
b7015f1fcf2be711ce463da8244b47d1f581c6df67551e4500d69ddcd2542879  /tmp/tmp.oda7hUDyqL/out/release/lianad
darosior@darosior:~/projects/revault/liana$ sha256sum /tmp/tmp.g9DQRYjTCl/out/gui/release/liana-gui
6fb1dc681a980a4a622d4532906faef447daa2a6a1307a2571c628252b366ac2  /tmp/tmp.g9DQRYjTCl/out/gui/release/liana-gui
```

**Comment by darosior** [comment]
Builds of @edouardparis on 592c1cbaa8f4c1cd27f33a1600c8ddeac3add3b0:
```
liana on  HEAD (592c1cb) is 📦 v0.0.1 via 🦀 v1.60.0 took 4m43s 
❯ sha256sum /tmp/tmp.w2GVH2IyeU/out/release/lianad
08e335f3e0740909cfb8d881a5c8ab7d3b8b35e207346f837c2bde16d7d8b1fb  /tmp/tmp.w2GVH2IyeU/out/release/lianad

liana on  HEAD (592c1cb) is 📦 v0.0.1 via 🦀 v1.60.0 
❯ sha256sum /tmp/tmp.w2GVH2IyeU/out/gui/release/liana-gui
6fb1dc681a980a4a622d4532906faef447daa2a6a1307a2571c628252b366ac2  /tmp/tmp.w2GVH2IyeU/out/gui/release/liana-gui
```

**Comment by darosior** [comment]
So Edouard pointed out this currently links against glibc version `2.33`, which is kinda unreasonable. For instance Debian stable and some LTS of Ubuntu still have inferior libc: https://sourceware.org/glibc/wiki/Release.

I think it would be reasonable to link against 2.27. Unfortunately i think we'd need to recompile Rust to link it against 2.27 too. My approach was to define a custom `gcc-toolchain` like so:
```diff
diff --git a/contrib/guix/build.sh b/contrib/guix/build.sh
index 7c9f00a..7178dc4 100755
--- a/contrib/guix/build.sh
+++ b/contrib/guix/build.sh
@@ -26,7 +26,7 @@ EOF
 
 # We need to set RUSTC_BOOTSTRAP=1 as a workaround to be able to use unstable
 # features in the GUI dependencies
-RUSTC_BOOTSTRAP=1 cargo -vvv \
+RUST_BACKTRACE=1 RUSTC_BOOTSTRAP=1 cargo -vvv \
     --color always \
     --frozen \
     --offline \
diff --git a/contrib/guix/manifest.scm b/contrib/guix/manifest.scm
index 5ea7a81..04f36f5 100644
--- a/contrib/guix/manifest.scm
+++ b/contrib/guix/manifest.scm
@@ -1,15 +1,31 @@
-(specifications->manifest
+(use-modules (gnu)
+             (gnu packages)
+             (gnu packages base)
+             (gnu packages commencement)
+             (gnu packages elf)
+             (gnu packages fontutils)
+             (gnu packages pkg-config)
+             (gnu packages linux)
+             (gnu packages rust)
+             (gnu packages gcc)
+             (guix packages))
+
+(define-public gcc-glibc-2.29-toolchain
+  (make-gcc-toolchain gcc glibc-2.29))
+
+(packages->manifest
   (append
-    (list "rust"
-          "rust:cargo"
-          "coreutils"
-          "patchelf"
-          "gcc-toolchain@10.3.0")
+    (list rust
+          (list rust "cargo")
+          coreutils
+          patchelf
+          gcc-toolchain
+          gcc-glibc-2.29-toolchain)
           ;; Additional dependencies for building the GUI
           (let ((binary_name (getenv "BINARY_NAME")))
             (if
               (string=? binary_name "liana-gui")
-              (list "pkg-config"
-                    "eudev"
-                    "fontconfig")
+              (list pkg-config
+                    eudev
+                    fontconfig)
               '()))))
```

But that's failing with a segfault. I think it's because Rust isn't linked to the same glibc in the substitute i'm using.

**Comment by darosior** [comment]
So i've been trying to rebuild the dependency graph using an earlier glibc (2.29) but i keep hitting random failures when building dependencies. I'm afraid we'll have to go with 2.33...

**Comment by darosior** [comment]
Rebased on master

**Comment by darosior** [comment]
I can't continue wasting on this. We'll unfortunately have to require a relatively recent libc. My latest attempt for posterity:
```diff
diff --git a/contrib/guix/guix-build.sh b/contrib/guix/guix-build.sh
index 816b346..0ff0363 100755
--- a/contrib/guix/guix-build.sh
+++ b/contrib/guix/guix-build.sh
@@ -130,6 +130,7 @@ for project_folder in "" "gui"; do
                --pure \
                --fallback \
                --rebuild-cache \
+               --keep-failed \
                -m $PWD/contrib/guix/manifest.scm \
                -- env CC=gcc VENDOR_DIR="$PROJECT_VENDOR_DIR" TARGET_DIR="$PROJECT_OUT_DIR" BINARY_NAME="$BINARY_NAME" JOBS="$JOBS" \
                   /bin/sh -c "cd /liana && ./build.sh"
diff --git a/contrib/guix/manifest.scm b/contrib/guix/manifest.scm
index 5ea7a81..da0e95d 100644
--- a/contrib/guix/manifest.scm
+++ b/contrib/guix/manifest.scm
@@ -1,15 +1,29 @@
-(specifications->manifest
+(use-modules (gnu packages commencement)
+             (gnu packages elf)
+             (gnu packages fontutils)
+             (gnu packages pkg-config)
+             (gnu packages rust)
+             (gnu packages gcc)
+             (guix packages))
+
+(define gcc-glibc-2.29-toolchain
+  (make-gcc-toolchain gcc-9 glibc-2.29))
+
+(define rust-glibc-2.29
+  (package-with-c-toolchain rust `(("gcc" ,gcc-glibc-2.29-toolchain))))
+
+(packages->manifest
   (append
-    (list "rust"
-          "rust:cargo"
-          "coreutils"
-          "patchelf"
-          "gcc-toolchain@10.3.0")
+    (list rust-glibc-2.29
+          coreutils
+          patchelf
+          gcc-toolchain
+          gcc-glibc-2.29-toolchain)
           ;; Additional dependencies for building the GUI
           (let ((binary_name (getenv "BINARY_NAME")))
             (if
               (string=? binary_name "liana-gui")
-              (list "pkg-config"
-                    "eudev"
-                    "fontconfig")
+              (list pkg-config
+                    eudev
+                    fontconfig)
               '()))))
```

**Comment by darosior** [comment]
I'd like to get this in, i'll PR Windows/MacOS reproducible builds separately.

ACK 72966b7bc98328e205c1405fd5e6c84d9c8a7509

**Comment by darosior** [comment]
Rebased.

ACK ef20b782301bae2fdfb842dfd89a749e60cb449e

**Comment by DesobedienteTecnologico** [comment]
Hi! thanks for this amazing project.

I'm about to add Liana in [DTails](https://github.com/DesobedienteTecnologico/dtails). But I got error with the GLib version. I now that is a know issue, but just wanted to see if there is some process with it?

image

---

image


Thanks and regards!

**Comment by darosior** [comment]
Hey @DesobedienteTecnologico. Thanks for your interest in Liana.

I'm planning to have another look at building against an older glibc before releasing 1.0 if i have time (#414). Another thing we could do as mentioned above is to try to statically build against musl. Unfortunately we don't have time to prioritise this at the moment, but it's definitely something i'd like to get back at working on (or would be happy to review a PR for).

**Comment by DesobedienteTecnologico** [comment]
> Hey @DesobedienteTecnologico. Thanks for your interest in Liana.
> 
> I'm planning to have another look at building against an older glibc before releasing 1.0 if i have time (#414). Another thing we could do as mentioned above is to try to statically build against musl. Unfortunately we don't have time to prioritise this at the moment, but it's definitely something i'd like to get back at working on (or would be happy to review a PR for).

I will try to compile it when I get time. It doesn't see that trivial to get that change working.

**Pull request merged**
